package com.improve1.pgmtCarShopPr1.controllers;

import com.improve1.pgmtCarShopPr1.models.Sproduct;
import com.improve1.pgmtCarShopPr1.repositories.StudentsRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.*;

@Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class GreetingController {
	// This means to get the bean called userRepository
	// Which is auto-generated by Spring, we will use it to handle the data
	@Autowired
	private StudentsRepository studentRepository;

	@GetMapping("/greeting")
	public String greeting(@RequestParam(name="name", required=false, defaultValue="World") String name, Model model) {
		model.addAttribute("name", name);
		return "greeting";
	}


	@PostMapping(path="/add") // Map ONLY POST Requests
	public @ResponseBody String addNewStudent (@RequestParam String name
			, @RequestParam String email) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		Sproduct n = new Sproduct();
		n.setName(name);
		n.setEmail(email);
		studentRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<Sproduct> getAllUsers() {
		// This returns a JSON or XML with the users
		return studentRepository.findAll();
	}

}